### PR TITLE
Fix gcc specific includes

### PR DESCRIPTION
**Pull request by qqwertyui**

### CODE REVIEW

**Comment by adambadura** [comment]
Thanks @qqwertyui ! However, I think it would be better to do the opposite - rename the files. The form with `.` instead of `_` seems more standard and hence easier for integration and automation. While it seems no real "integration and automation" will be happening here, but still it seems to me this would be better.

Will you care to change your pull request so that your contribution of spotting the error remains clear?

**Comment by qqwertyui** [comment]
Sure, I will take care of the changes

**Comment by qqwertyui** [comment]
done

**Comment by adambadura** [comment]
Thanks!

**Pull request merged**
